demo_dbt:
  target: prod
  outputs:
    prod:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: dbcontent6848.footfallcam.com
      port: 41433
      database: Airbyte
      schema: dbo
      user: usr_airbyte
      password: Qairbyte!234
      encrypt: False